// Code generated by cmd/cgo; DO NOT EDIT.

//line D:\workspace\go\src\magic.engine\plus\navigatior\navigatior.go:1:1
package navigatior

/*
#cgo CFLAGS: -I ${SRCDIR}/include
#cgo CXXFLAGS: -I ${SRCDIR}/include -I ${SRCDIR}/include/navigator -I ${SRCDIR}/include/detour
#cgo lnavigation LDFLAGS: -lnavigation
#cgo navigationa LDFLAGS: -lnavigation -lm -ldl
#cgo linux,!lnavigation,!navigationa LDFLAGS: -L${SRCDIR}/linux -lnavigation
#cgo darwin,!lnavigation,!navigationa LDFLAGS: -lnavigation
#cgo freebsd,!navigationa LDFLAGS: -lnavigation
#cgo windows,!lnavigation LDFLAGS: -L${SRCDIR}/win64 -lnavigation -lmingwex -lmingw32


#include <stdlib.h>

#include "gonavigatior.h"
*/
import _ "unsafe"

type Navigatior struct {
	_nav * /*line :21:8*/_Ctype_struct_GONavigatior /*line :21:29*/
}
